FROM python:3.13-slim@sha256:b04b5d7233d2ad9c379e22ea8927cd1378cd15c60d4ef876c065b25ea8fb3bf3

RUN pip install -U pip

WORKDIR /api_tests

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

CMD ["pytest", "."]
