title: ReductStore
name: reductstore # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.3.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A time series database for storing and managing large amounts of blob data # 79 char long summary
description: |
  ReductStore is a time series database designed specifically for storing and managing
  large amounts of blob data. It has high performance for writing and real-time querying,
  making it suitable for edge computing, computer vision, and IoT applications.
  ReductStore is 100% open source under Mozilla Public License v2.0.
contact: info@reduct.store
issues: https://github.com/reductstore/reductstore/issues
source-code: https://github.com/reductstore/reductstore.git
website: https://wwww.reduct.store
license: MPL-2.0
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
- build-on: arm64
- build-on: amd64
parts:
  reductstore:
    # See 'snapcraft plugins'
    plugin: cmake
    source: .
    source-type: local
    cmake-parameters:
    - -DCMAKE_BUILD_TYPE=Release
    - -DREDUCT_BUILD_TEST=OFF
    - -DREDUCT_BUILD_BENCHMARKS=OFF
    override-build: |
      pip3 install conan==1.58
      snapcraftctl build

    build-packages:
      - g++
      - make
      - python3-pip

    stage-packages:
      - libstdc++6
apps:
  reductstore:
    command: usr/local/bin/reductstore
    plugs:
      - network
      - network-bind
      - home
      - removable-media
