name: 'AWS Credentials and Cargo Cache'
description: 'Configures AWS credentials via OIDC and sets up Cargo cache.'
inputs:
  target:
    description: 'Target triple.'
    required: true
  profile:
    description: 'Cargo profile used for the build.'
    required: false
    default: 'ci'
runs:
  using: 'composite'
  steps:
    - name: Detect rust minor version
      shell: bash
      run: |
        if [[ -z "${RUST_MINOR:-}" ]]; then
          minor=$(rustc --version --verbose | sed -ne 's/^release: \([0-9]*\.[0-9]*\).*/\1/p')
          echo "RUST_MINOR=${minor:-unknown}" >> "$GITHUB_ENV"
        else
          echo "Using preset RUST_MINOR=${RUST_MINOR}"
        fi

    - name: Configure AWS credentials via OIDC (org-wide role)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.S3_CACHE_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.S3_CACHE_SECRET_KEY }}
        aws-region: eu-central

    - name: Use cache for Cargo
      uses: runs-on/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-${{ inputs.target }}-${{ inputs.profile }}-cargo-rust${{ env.RUST_MINOR }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.target }}-${{ inputs.profile }}-cargo-rust${{ env.RUST_MINOR }}-
          ${{ runner.os }}-${{ inputs.target }}-${{ inputs.profile }}-cargo-
      env:
        RUNS_ON_S3_BUCKET_CACHE: reduct-cache
        RUNS_ON_S3_BUCKET_ENDPOINT: reduct-cache.fsn1.your-objectstorage.com
