name: 'AWS Credentials and Cargo Cache'
description: 'Configures AWS credentials via OIDC and sets up Cargo cache.'
inputs:
  target:
    description: 'Target triple.'
    required: true
  profile:
    description: 'Cargo profile used for the build.'
    required: false
    default: 'ci'
runs:
  using: 'composite'
  steps:
    - name: Detect rust minor version
      shell: bash
      run: |
        minor=$(rustc --version --verbose | sed -ne 's/^release: \([0-9]*\.[0-9]*\).*/\1/p')
        echo "RUST_MINOR=${minor:-unknown}" >> "$GITHUB_ENV"

    - name: Configure AWS credentials via OIDC (org-wide role)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::800293099462:role/gha-s3-cache-multi-repo
        aws-region: us-east-1

    - name: Use cache for Cargo
      uses: runs-on/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/${{ inputs.target }}/
        key: ${{ runner.os }}-${{ inputs.target }}-${{ inputs.profile }}-cargo-rust${{ env.RUST_MINOR }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.target }}-${{ inputs.profile }}-cargo-rust${{ env.RUST_MINOR }}-
          ${{ runner.os }}-${{ inputs.target }}-${{ inputs.profile }}-cargo-
      env:
        RUNS_ON_S3_BUCKET_CACHE: reduct-github-cache
