name: 'Recovery Test'
description: 'Runs recovery tests for ReductStore.'
inputs:
  cmd:
    description: 'Docker command to stop or kill.'
    required: true
  rs_api_token:
    description: 'API token for ReductStore.'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: image
        path: /tmp/

    - name: Load image
      shell: bash
      run: |
        docker load --input /tmp/image.tar
        docker image ls -a

    - name: Prepare data volume
      shell: bash
      run: |
        DATA_VOLUME="reductstore-recovery-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
        echo "DATA_VOLUME=$DATA_VOLUME" >> "$GITHUB_ENV"
        docker volume create "$DATA_VOLUME"

    - name: Run ReductStore with FileSystem backend
      shell: bash
      run: |
        docker run --network=host -v "${DATA_VOLUME}:/data" --env RS_API_TOKEN=${{ inputs.rs_api_token }} --name reductstore -d ${{ inputs.repository }}
        sleep 5
        docker logs reductstore


    - name: Upload data
      shell: bash
      env:
        RS_API_TOKEN: ${{ inputs.rs_api_token }}
      run: |
        pip install -r ./integration_tests/data_check/requirements.txt
        python3 ./integration_tests/data_check/uploader.py

    - name: Restart ReductStore
      shell: bash
      run: |
        docker ${{ inputs.cmd }} reductstore
        docker run --network=host -v "${DATA_VOLUME}:/data" --env RS_API_TOKEN=${{ inputs.rs_api_token }} --name reductstore-1 -d ${{ inputs.repository }}
        sleep 5
        docker logs reductstore-1

    - name: Check data after migration
      shell: bash
      env:
          RS_API_TOKEN: ${{ inputs.rs_api_token }}
      run: python3 ./integration_tests/data_check/checker.py

    - name: Save docker logs
      if: always()
      shell: bash
      run: docker logs reductstore | zip > /tmp/docker-log.zip

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: docker-log-recovery-${{ inputs.cmd }}
        path: /tmp/docker-log.zip

    - name: Show replication report
      if: always()
      shell: bash
      run: cat ./report.json
