name: 'Build Binaries'
description: 'Builds binaries for a specific target and uploads them as artifacts.'
inputs:
  minimal_rust_version:
    description: 'Minimal Rust version.'
    required: true
  action_github_token:
    description: 'GitHub token for setup-protoc.'
    required: true
  target:
    description: 'Target triple.'
    required: true
  os:
    description: 'Operating system.'
    required: true
  compiler:
    description: 'Compiler package name.'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: arduino/setup-protoc@v3
      with:
        version: '26.x'
        repo-token: ${{ inputs.action_github_token }}
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ inputs.minimal_rust_version }}
    - name: Install toolchain
      run: rustup target add ${{ inputs.target }}
    - name: Install gcc (Linux)
      if: ${{ inputs.os == 'ubuntu-24.04' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.compiler }}
    - name: Install gcc (macOS)
      if: ${{ inputs.os == 'macos-latest' }}
      run: |
        brew install ${{ inputs.compiler }}
    - uses: ilammy/setup-nasm@v1
    - name: Install cargo-export
      run: cargo install cargo-export
    - name: Build binary (PR)
      if: github.event_name == 'pull_request'
      env:
        RUSTFLAGS: "-C target-feature=+crt-static"
      run: cargo build --profile ci -p reductstore --target ${{ inputs.target }} --all-features
    - name: Build binary (Release)
      if: github.event_name != 'pull_request'
      env:
        RUSTFLAGS: "-C target-feature=+crt-static"
      run: cargo build --profile release -p reductstore --target ${{ inputs.target }} --all-features
    - name: Upload binary (Release)
      uses: actions/upload-artifact@v4
      if: github.event_name != 'pull_request'
      with:
        name: reductstore-${{ inputs.target }}
        path: target/${{inputs.target}}/release/reductstore${{ inputs.target == 'x86_64-pc-windows-gnu' && '.exe' || '' }}
        if-no-files-found: 'error'
    - name: Build and export tests (PR)
      if: github.event_name == 'pull_request'
      run: cargo export target/${{ inputs.target }}/tests -- test --profile ci --target ${{ inputs.target }} --lib
    - name: Build and export tests (Release)
      if: github.event_name != 'pull_request'
      run: cargo export target/${{ inputs.target }}/tests -- test --profile release --target ${{ inputs.target }} --lib
    - name: Upload tests
      uses: actions/upload-artifact@v4
      with:
        name: reductstore-tests-${{ inputs.target }}
        path: target/${{ inputs.target }}/tests
