name: 'Replication Test'
description: 'Runs replication tests for ReductStore.'
inputs:
  max_blob_size:
    description: 'Maximum blob size in MB.'
    required: true
  entries:
    description: 'Number of entries.'
    required: true
  records:
    description: 'Number of records.'
    required: true
  rs_api_token:
    description: 'API token for ReductStore.'
    required: true
  repository:
    description: 'GitHub repository.'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: image
        path: /tmp/

    - name: Load image
      shell: bash
      run: |
        docker load --input /tmp/image.tar
        docker image ls -a
    - name: Run current ReductStore
      shell: bash
      run: |
        docker run --network=host -v ./data:/data \
          --env RS_LOG_LEVEL=DEBUG \
          --env RS_API_TOKEN=${{ inputs.rs_api_token }} \
          --env RS_BUCKET_1_NAME=src \
          --env RS_BUCKET_2_NAME=dest \
          --env RS_REPLICATION_1_NAME=replication \
          --env RS_REPLICATION_1_SRC_BUCKET=src \
          --env RS_REPLICATION_1_DST_BUCKET=dest \
          --env RS_REPLICATION_1_DST_HOST=http://127.0.0.1:8383 \
          --env RS_REPLICATION_1_DST_TOKEN=${{ inputs.rs_api_token }} \
          --name current -d ${{ inputs.repository }}
        sleep 5
        docker logs current

    - name: Upload data
      shell: bash
      env:
        RS_API_TOKEN: ${{ inputs.rs_api_token }}
        BUCKET_NAME: src
        NUMBER_OF_ENTRIES: ${{ inputs.entries }}
        NUMBER_OF_RECORDS: ${{ inputs.records }}
        MAX_BLOB_SIZE: ${{ inputs.max_blob_size }}
      run: |
        pip install -r ./integration_tests/data_check/requirements.txt
        python3 ./integration_tests/data_check/uploader.py
        sleep 30 # Wait for replication

    - name: Check replicated data
      shell: bash
      env:
        RS_API_TOKEN: ${{ inputs.rs_api_token }}
        BUCKET_NAME: dest
      run: python3 ./integration_tests/data_check/checker.py

    - name: Save docker logs
      if: always()
      shell: bash
      run: docker logs current | zip > /tmp/docker-log.zip

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: docker-log-repl-${{ inputs.max_blob_size }}
        path: /tmp/docker-log.zip

    - name: Show replication report
      if: always()
      shell: bash
      run: cat ./report.json

    - name: Show replication status
      if: always()
      shell: bash
      run: |
        curl -H "Authorization: Bearer ${{ inputs.rs_api_token }}" http://127.0.0.1:8383/api/v1/replications/replication | jq
