name: 'Read-Only Replica Test'
description: 'Runs read-only replica integration tests for ReductStore.'
inputs:
  rs_api_token:
    description: 'API token for ReductStore.'
    required: true
  repository:
    description: 'GitHub repository.'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Download Docker image artifact
      uses: actions/download-artifact@v4
      with:
        name: image
        path: /tmp/

    - name: Load Docker image
      shell: bash
      run: |
        docker load --input /tmp/image.tar
        docker image ls -a


    - name: Start primary and replica instances
      shell: bash
      run: |
        set -euo pipefail

        data_volume="reductstore-read-only-replica-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
        echo "DATA_VOLUME=$data_volume" >> "$GITHUB_ENV"
        docker volume rm "$data_volume" >/dev/null 2>&1 || true
        docker volume create "$data_volume"

        primary_env=(
          --env RS_INSTANCE_ROLE=PRIMARY
          --env RS_PORT=8383
          --env RS_API_TOKEN=${{ inputs.rs_api_token }}
          --env RS_LOG_LEVEL=DEBUG
          --env RS_ENGINE_COMPACTION_INTERVAL=3
          --env RS_ENGINE_REPLICA_UPDATE_INTERVAL=3
          --env RS_REMOTE_SYNC_INTERVAL=3
          --env RS_DATA_PATH=/data
        )

        replica_env=(
          --env RS_INSTANCE_ROLE=REPLICA
          --env RS_PORT=8384
          --env RS_API_TOKEN=${{ inputs.rs_api_token }}
          --env RS_LOG_LEVEL=DEBUG
          --env RS_ENGINE_COMPACTION_INTERVAL=3
          --env RS_ENGINE_REPLICA_UPDATE_INTERVAL=3
          --env RS_REMOTE_SYNC_INTERVAL=3
          --env RS_DATA_PATH=/data
        )

        docker run --network=host -v "$data_volume:/data" \
          "${primary_env[@]}" \
          --name reduct-primary -d ${{ inputs.repository }}

        docker run --network=host -v "$data_volume:/data" \
          "${replica_env[@]}" \
          --name reduct-replica -d ${{ inputs.repository }}

        docker ps --filter "name=reduct-primary"
        docker ps --filter "name=reduct-replica"

        for _ in {1..60}; do
          if curl -fsS "http://127.0.0.1:8383/api/v1/ready" >/dev/null 2>&1; then
            break
          fi
          sleep 1
        done
        curl -fsS "http://127.0.0.1:8383/api/v1/ready" >/dev/null 2>&1

        for _ in {1..60}; do
          if curl -fsS "http://127.0.0.1:8384/api/v1/ready" >/dev/null 2>&1; then
            break
          fi
          sleep 1
        done
        curl -fsS "http://127.0.0.1:8384/api/v1/ready" >/dev/null 2>&1

    - name: Debug container mounts and env
      if: ${{ always() }}
      shell: bash
      run: |
        set -euo pipefail
        echo "Primary mounts:"
        docker inspect reduct-primary --format 'Mounts: {{json .Mounts}}'
        docker inspect reduct-primary --format 'Env: {{json .Config.Env}}'
        echo "Replica mounts:"
        docker inspect reduct-replica --format 'Mounts: {{json .Mounts}}'
        docker inspect reduct-replica --format 'Env: {{json .Config.Env}}'
        if docker ps --format '{{.Names}}' | grep -q '^minio-server$'; then
          echo "MinIO mounts:"
          docker inspect minio-server --format 'Mounts: {{json .Mounts}}'
          docker inspect minio-server --format 'Env: {{json .Config.Env}}'
        fi

    - name: Run read-only replica tests
      shell: bash
      env:
        PRIMARY_STORAGE_URL: http://127.0.0.1:8383
        REPLICA_STORAGE_URL: http://127.0.0.1:8384
        API_TOKEN: ${{ inputs.rs_api_token }}
      run: |
        pip install -r ./integration_tests/deployment/requirements.txt
        pytest integration_tests/deployment/read_only_replica_test.py

    - name: Print docker logs
      if: always()
      shell: bash
      run: |
        docker logs reduct-primary || true
        docker logs reduct-replica || true

    - name: Cleanup docker containers
      if: always()
      shell: bash
      run: |
        docker rm -f reduct-primary || true
        docker rm -f reduct-replica || true
        docker volume rm "${DATA_VOLUME}" >/dev/null 2>&1 || true
