title: ReductStore
name: reductstore # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
adopt-info: reductstore
summary: High Performance Data Storage and Streaming for Robotics and Industrial IoT # 79 char long summary
description: |
  ReductStore is a high-performance, time-series object storage and streaming solution for ELT-based data acquisition (DAQ) systems in robotics and industrial IoT (IIoT).
  It's designed to handle large volumes of unstructured data - images, sensor readings, logs, files, ROS bags - captured in raw form and stored with a precise time index (timestamp) and optional labels (e.g. device status, AI inference). This enables fast, efficient retrieval based on when the data was collected and how it's categorized, while also allowing control over data reduction strategies by replicating (streaming) only selected data from the edge to the cloud.

contact: info@reduct.store
issues: https://github.com/reductstore/reductstore/issues
source-code: https://github.com/reductstore/reductstore.git
website: https://wwww.reduct.store
license: Apache-2.0
confinement: strict # use 'strict' once you have the right plugs and slots
grade: stable # must be 'stable' to release into candidate/stable channels

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [amd64]
    build-for: [arm64]
parts:
  reductstore:
    plugin: dump
    source: .snap-build/bin
    organize:
      reductstore: bin/reductstore
  hooks:
    plugin: dump
    source: snap/local/hooks
    organize:
      bin/: snap/hooks/
  scripts:
    plugin: dump
    source: snap/local/scripts


apps:
  reductstore:
    command: bin/wrapper
    daemon: simple
    restart-condition: on-failure
    plugs:
      - network
      - network-bind
      - removable-media
      - home

    plugin: dump
    source: snap/local/hooks
    organize:
      bin/: snap/hooks/
  scripts:
    plugin: dump
    source: snap/local/scripts


apps:
  reductstore:
    command: bin/wrapper
    daemon: simple
    restart-condition: on-failure
    plugs:
      - network
      - network-bind
      - removable-media
      - home
