title: ReductStore
name: reductstore # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info:  reductstore  # use the upstream version number for the snap version
summary: A time series database for storing and managing large amounts of blob data # 79 char long summary
description: |
  ReductStore is a time series database designed specifically for storing and managing
  large amounts of blob data. It has high performance for writing and real-time querying,
  making it suitable for edge computing, computer vision, and IoT applications.
  ReductStore is 100% open source under Mozilla Public License v2.0.
contact: info@reduct.store
issues: https://github.com/reductstore/reductstore/issues
source-code: https://github.com/reductstore/reductstore.git
website: https://wwww.reduct.store
license: MPL-2.0
confinement: strict # use 'strict' once you have the right plugs and slots
grade: stable # must be 'stable' to release into candidate/stable channels

architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: amd64
    build-for: arm64
parts:
  reductstore:
    # See 'snapcraft plugins'
    plugin: rust
    source: .
    source-type: local
    rust-path: ["reductstore"]

    override-pull: |
      craftctl default
      cargo install cargo-get
      VERSION="$(cargo-get get package.version --entry reductstore/)-git$(git rev-parse --short HEAD)"
      echo "ReductStore v${VERSION}"
      echo "version: $VERSION" >> snap/snapcraft.yaml
    override-build: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      source "$HOME/.cargo/env"
      snapcraftctl build

    build-packages:
      - cargo
      - protobuf-compiler
      - libprotobuf-dev
  hooks:
    plugin: dump
    source: snap/local/hooks
    organize:
      bin/: snap/hooks/
  scripts:
    plugin: dump
    source: snap/local/scripts


apps:
  reductstore:
    command: bin/wrapper
    daemon: simple
    restart-condition: on-failure
    plugs:
      - network
      - network-bind
      - removable-media
      - home
