[package]
name = "reductstore"

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

license = "BUSL-1.1"
description = "ReductStore is a time series database designed specifically for storing and managing large amounts of blob data."
homepage = "https://reduct.store"
documentation = "https://docs.reduct.store"
repository = "https://github.com/reductstore/reductstore"

keywords = ["database", "time-series", "blob", "storage", "reductstore"]
categories = ["database-implementations", "command-line-utilities", "database"]
include = ["src/**/*", "Cargo.toml", "Cargo.lock", "build.rs", "README.md", "LICENSE"]

[features]
default = ["web-console"]
web-console = []

[lib]
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reduct-base =  { path = "../reduct_base", version = "1.8.0-dev" }
reduct-macros = { path = "../reduct_macros", version = "1.8.0-dev" }

log = "0.4.20"
chrono = { version = "0.4.26", features = ["serde"] }
thread-id = "4.1.0"
zip = "0.6.6"
tempfile = "3.8.0"
hermit-abi = "0.3.2"
hex = "0.4.3"
prost = "0.11.9"
prost-wkt = "0.4.2"
prost-wkt-types = "0.4.2"
rand = "0.8.5"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
regex = "1.9.3"
bytes = "1.4.0"
axum = { version = "0.6.20", features = ["default", "headers"] }
tokio = { version = "1.32.0", features = ["full"] }
hyper = { version = "0.14.27", features = ["full"] }
tower = "0.4.13"
futures-util = "0.3.28"
tokio-util = "0.7.8"
axum-server = { version = "0.5.1", features = ["tls-rustls"] }
rustls = "0.21.6"
mime_guess = "2.0.4"
bytesize = "1.3.0"
axum-macros = "0.3.8"

[build-dependencies]
prost-build = "0.12.1"
prost-wkt-build = "0.4.2"
reqwest = { version = "0.11.6", default-features = false, features = ["rustls-tls", "blocking"] }
chrono = "0.4.26"

[dev-dependencies]
mockall = "0.11.4"
rstest = "0.18.2"


[package.metadata.docs.rs]
no-default-features = true
