[package]
name = "reductstore"

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

license = "BUSL-1.1"
description = "ReductStore is a time series database designed specifically for storing and managing large amounts of blob data."
homepage = "https://reduct.store"
documentation = "https://reduct.store/docs"
repository = "https://github.com/reductstore/reductstore"

keywords = ["database", "time-series", "blob", "storage", "reductstore"]
categories = ["database-implementations", "command-line-utilities", "database"]
include = ["src/**/*", "Cargo.toml", "Cargo.lock", "build.rs", "README.md", "LICENSE"]

[features]
default = ["web-console"]
web-console = []

[lib]
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reduct-base =  { path = "../reduct_base", version = "1.8.1" }
reduct-macros = { path = "../reduct_macros", version = "1.8.1" }
reduct-rs = { path = "../reduct_rs", version = "1.8.1" }

log = "0.4.20"
chrono = { version = "0.4.31", features = ["serde"] }
thread-id = "4.2.1"
zip = "0.6.6"
tempfile = "3.9.0"
hermit-abi = "0.3.3"
hex = "0.4.3"
prost = "0.12.3"
prost-wkt = "0.5.0"
prost-wkt-types = "0.5.0"
rand = "0.8.5"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.110"
regex = "1.10.2"
bytes = "1.5.0"
axum = { version = "0.6.20", features = ["default", "headers"] }
tokio = { version = "1.32.0", features = ["full"] }
hyper = { version = "0.14.28", features = ["full"] }
tower = "0.4.13"
futures-util = "0.3.30"
tokio-util = "0.7.10"
axum-server = { version = "0.5.1", features = ["tls-rustls"] }
rustls = "0.22.1"
mime_guess = "2.0.4"
bytesize = "1.3.0"
async-trait="0.1.77"
url = { version = "2.5.0", features = ["serde"] }

[build-dependencies]
prost-build = "0.12.3"
prost-wkt-build = "0.5.0"
reqwest = { version = "0.11.23", default-features = false, features = ["rustls-tls", "blocking"] }
chrono = "0.4.31"

[dev-dependencies]
mockall = "0.12.1"
rstest = "0.18.2"


[package.metadata.docs.rs]
no-default-features = true
