name: build and upload binaries and tests
on:
  workflow_run:
    workflows:
      - "lint and check tag"
    types:
      - completed
jobs:
  build:
    name: Build Linux Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          file: buildx.Dockerfile
          tags: ${{github.repository}}:latest
          outputs: type=docker,dest=/tmp/image.tar
          build-args: |
            ARTIFACT_SAS_URL=${{ secrets.ARTIFACT_SAS_URL }}
            RUST_VERSION=${{ vars.MINIMAL_RUST_VERSION }}
            BUILD_PROFILE=ci

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: /tmp/image.tar
