name: publish snap
on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed

jobs:
  publish_crate:
    runs-on: ubuntu-latest
    name: Publish crate
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ vars.MINIMAL_RUST_VERSION }}
      - uses: arduino/setup-protoc@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.ACTION_GITHUB_TOKEN }}
      - name: Login
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish reduct-base
        run: cargo publish -p reduct-base
      - name: Publish reduct-macros
        run: cargo publish -p reduct-macros
      - name: Publish reductstore
        run: cargo publish -p reductstore
